spring:
  application:
    name: itoken-eureka
  boot:
    admin:
      client:
        url: http://192.168.184.135:8084
  zipkin:
    base-url: http://192.168.184.135:9411

server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.184.135
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info